sudo: required
language: python
services:
  - mysql
env:
  - TZ=Europe/Kaliningrad PYTRAINER_ALCHEMYURL="sqlite://"
  - TZ=Europe/Kaliningrad PYTRAINER_ALCHEMYURL="mysql://pytrainer@localhost/pytrainer?charset=utf8"
before_install:
  - sudo apt-get install --no-install-recommends python-gtk2 python-glade2 python-lxml python-matplotlib python-tornado
  - mysql -e "CREATE USER 'pytrainer'@'localhost';"
  - mysql -e "CREATE DATABASE pytrainer;"
  - mysql -e "GRANT ALL PRIVILEGES ON pytrainer . * TO 'pytrainer'@'localhost';"
python:
  - "2.7"
script: "python setup.py test"
virtualenv:
  system_site_packages: true
notifications:
  irc:
    channels: "ircs://chat.freenode.net:7000/#pytrainer"
